//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roham.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roham.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache provider {0} is not supported..
        /// </summary>
        public static string CacheProviderNotSupported {
            get {
                return ResourceManager.GetString("CacheProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache server cannot be connected..
        /// </summary>
        public static string CacheServerCannotBeConnected {
            get {
                return ResourceManager.GetString("CacheServerCannotBeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file is missing..
        /// </summary>
        public static string ConfigFileMissing {
            get {
                return ResourceManager.GetString("ConfigFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cannot be connected..
        /// </summary>
        public static string DatabaseConnectionFailed {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cannot be created, please check application log for more details..
        /// </summary>
        public static string DatabaseCreationFailed {
            get {
                return ResourceManager.GetString("DatabaseCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database initialization failed..
        /// </summary>
        public static string DatabaseInitializationFailed {
            get {
                return ResourceManager.GetString("DatabaseInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is down. .
        /// </summary>
        public static string DatabaseIsDown {
            get {
                return ResourceManager.GetString("DatabaseIsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue with database settings..
        /// </summary>
        public static string DatabaseSettingsInvalid {
            get {
                return ResourceManager.GetString("DatabaseSettingsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database upgrade failed..
        /// </summary>
        public static string DatabaseUpgradeFailed {
            get {
                return ResourceManager.GetString("DatabaseUpgradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database provider {0} is not supported..
        /// </summary>
        public static string DataProviderNotSupported {
            get {
                return ResourceManager.GetString("DataProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be sent at the moment, please try later..
        /// </summary>
        public static string EmailCannotbeSent {
            get {
                return ResourceManager.GetString("EmailCannotbeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email server cannot be connected..
        /// </summary>
        public static string EmailServerCannotBeConnected {
            get {
                return ResourceManager.GetString("EmailServerCannotBeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed, please check application log for more details..
        /// </summary>
        public static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation key is not valid..
        /// </summary>
        public static string InstallationKeyInvalid {
            get {
                return ResourceManager.GetString("InstallationKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is invalid..
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm password should match..
        /// </summary>
        public static string PasswordAndConfirmShouldMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmShouldMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error occured..
        /// </summary>
        public static string SystemErrorOccured {
            get {
                return ResourceManager.GetString("SystemErrorOccured", resourceCulture);
            }
        }
    }
}
