//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roham.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScreenTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roham.Resources.ScreenTexts", typeof(ScreenTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already installed.
        ///No Upgrade required..
        /// </summary>
        public static string AppilcationAlreadyInstalled {
            get {
                return ResourceManager.GetString("AppilcationAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article zone is used to publish article entries. It gives you different perspectives based on categories, dates and tags to the article entries. .
        /// </summary>
        public static string ArticleZone_Description {
            get {
                return ResourceManager.GetString("ArticleZone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog zone is used to publish blog entries. It gives you different perspectives based on categories, dates and tags to the blog entries. .
        /// </summary>
        public static string BlogZone_Description {
            get {
                return ResourceManager.GetString("BlogZone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the Installation Key in order to install {0}.
        /// When installation key verfication succeeded, then you will be able to proceed with installation..
        /// </summary>
        public static string Install_KeyVerificationDescription {
            get {
                return ResourceManager.GetString("Install_KeyVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a blog engine developed by develpers to be used by developers. It give the opportunity to define multiple sites and within the site scope multiple zones and then post entries. 
        ///Please provide the required information in order to install {0}..
        /// </summary>
        public static string Installation_WelcomeText {
            get {
                return ResourceManager.GetString("Installation_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0} Installation.
        /// </summary>
        public static string Installation_WelcomeTitle {
            get {
                return ResourceManager.GetString("Installation_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab zone is used to publish entries relating to different exercises . There is no limitation for exercises&apos; entries content and they could be even inspired from a dream or trivial ideas..
        /// </summary>
        public static string LabZone_Description {
            get {
                return ResourceManager.GetString("LabZone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News zone is used to publish news and announcement entries..
        /// </summary>
        public static string NewsZone_Description {
            get {
                return ResourceManager.GetString("NewsZone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now, to configure your new portal as you like!.
        /// </summary>
        public static string Upgrade_DoneLoginText {
            get {
                return ResourceManager.GetString("Upgrade_DoneLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is up-to-date..
        /// </summary>
        public static string Upgrade_EverythingUpToDateText {
            get {
                return ResourceManager.GetString("Upgrade_EverythingUpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required to have access to this Page..
        /// </summary>
        public static string Upgrade_LoginRequiredText {
            get {
                return ResourceManager.GetString("Upgrade_LoginRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to check the upgrade status and do more configurations, if this is your portal..
        /// </summary>
        public static string Upgrade_LoginText {
            get {
                return ResourceManager.GetString("Upgrade_LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Upgrade Result.
        /// </summary>
        public static string Upgrade_ResultText {
            get {
                return ResourceManager.GetString("Upgrade_ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikki zone gives you the opportunity to publish informative content which are used as wikkis..
        /// </summary>
        public static string WikkiZone_Description {
            get {
                return ResourceManager.GetString("WikkiZone_Description", resourceCulture);
            }
        }
    }
}
